package com.realestate.property.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@Entity
@Table(name = "properties", indexes = {
    @Index(name = "idx_city", columnList = "city"),
    @Index(name = "idx_type", columnList = "type"),
    @Index(name = "idx_status", columnList = "status"),
    @Index(name = "idx_transaction_type", columnList = "transaction_type"),
    @Index(name = "idx_price", columnList = "price"),
    @Index(name = "idx_agent_id", columnList = "agent_id"),
    @Index(name = "idx_created_at", columnList = "created_at")
})
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Property {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    @NotBlank(message = "Title is required")
    @Size(max = 200)
    @Column(nullable = false, length = 200)
    private String title;
    
    @NotBlank(message = "Description is required")
    @Size(max = 2000)
    @Column(nullable = false, length = 2000)
    private String description;
    
    @NotNull(message = "Property type is required")
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private PropertyType type;
    
    @NotNull(message = "Transaction type is required")
    @Enumerated(EnumType.STRING)
    @Column(name = "transaction_type", nullable = false, length = 20)
    private TransactionType transactionType; // SALE or RENTAL
    
    @NotNull(message = "Price is required")
    @DecimalMin(value = "0.0", inclusive = false)
    @Column(nullable = false, precision = 15, scale = 2)
    private BigDecimal price;
    
    // For rental properties - monthly rent
    @Column(name = "monthly_rent", precision = 15, scale = 2)
    private BigDecimal monthlyRent;
    
    // For rental properties - deposit amount
    @Column(name = "deposit_amount", precision = 15, scale = 2)
    private BigDecimal depositAmount;
    
    // Rental duration (in months) - null means indefinite
    @Column(name = "rental_duration")
    private Integer rentalDuration;
    
    @NotNull(message = "Surface is required")
    @Min(value = 1)
    @Column(nullable = false)
    private Integer surface;
    
    @NotNull(message = "Number of rooms is required")
    @Min(value = 0)
    @Column(nullable = false)
    private Integer rooms;
    
    @NotNull(message = "Number of bathrooms is required")
    @Min(value = 0)
    @Column(nullable = false)
    private Integer bathrooms;
    
    @NotBlank(message = "Address is required")
    @Size(max = 255)
    @Column(nullable = false)
    private String address;
    
    @NotBlank(message = "City is required")
    @Size(max = 100)
    @Column(nullable = false, length = 100)
    private String city;
    
    @Size(max = 20)
    @Column(length = 20)
    private String postalCode;
    
    @NotNull(message = "Status is required")
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private PropertyStatus status;
    
    @NotNull(message = "Agent ID is required")
    @Column(name = "agent_id", nullable = false)
    private Long agentId;
    
    // Additional features
    @Column(name = "has_parking")
    private Boolean hasParking;
    
    @Column(name = "has_garden")
    private Boolean hasGarden;
    
    @Column(name = "has_pool")
    private Boolean hasPool;
    
    @Column(name = "has_elevator")
    private Boolean hasElevator;
    
    @Column(name = "floor_number")
    private Integer floorNumber;
    
    @Column(name = "total_floors")
    private Integer totalFloors;
    
    @Column(name = "year_built")
    private Integer yearBuilt;
    
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;
    
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;
    
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
    }
    
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
    
    // Getters and Setters are generated by Lombok @Data annotation
    
    // Enums
    public enum PropertyType {
        APARTMENT, HOUSE, VILLA, LAND, COMMERCIAL, OFFICE, STUDIO, DUPLEX, PENTHOUSE
    }
    
    public enum TransactionType {
        SALE, RENTAL
    }
    
    public enum PropertyStatus {
        AVAILABLE, RESERVED, SOLD, RENTED, UNAVAILABLE
    }
}

